---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "AddLocalEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.25.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "7557a1b"
  parameters:
    - "description": "an editor for modifying this project"
    - "groupId": "local"
    - "editorName": "BumpVersion"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "f2aa478"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "f2aa478*"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "7b7ca77"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "0307615"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "dfa1baf"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "15bbd03"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "e8c9f3b"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.34.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "c35720f"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.34.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "dba57e8"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.34.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "56c1c2c"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.34.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "c85373e"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.34.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "b8925df"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.34.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "b4e1543"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.34.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "0b4d1bf"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.34.0"
editor:
  name: "BumpVersion"
  group: "local"
  artifact: "survey-elm"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/survey-elm.git"
    branch: "master"
    sha: "da79c88"
  parameters:
    - "component": "patch"

